spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001 #注册中心占用7001端口，冒号后面必须有空格
    
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        url: jdbc:mysql://localhost/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    mybatis:
        config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件所在的路径
        type-aliases-package: com.hec.springcloud.entities   #所有entitiy别名类所在的包
        mapper-locations: classpath:mybatis/mapper/**/*.xml  #mapper映射文件
    eureka:
        client:
            service-url:
                defaultZone: http://eureka7001.com:7001/eureka/
        instance:
            instance-id: dept-8001.com  #自定义服务名称信息 
            prefer-ip-address: true #访问路径可以显示Ip地址
    
    info:
        app.name: hec-microservicecloud
        company.name: www.hec.com
        build.artifactId: $project.artifactId$
        build.version: $project.version$
---    
spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        url: jdbc:mysql://localhost/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    mybatis:
        config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件所在的路径
        type-aliases-package: com.hec.springcloud.entities   #所有entitiy别名类所在的包
        mapper-locations: classpath:mybatis/mapper/**/*.xml  #mapper映射文件
    eureka:
        client:
            service-url:
                defaultZone: http://eureka7001.com:7001/eureka/
        instance:
            instance-id: dept-8001.com  #自定义服务名称信息 
            prefer-ip-address: true #访问路径可以显示Ip地址
    
    info:
        app.name: hec-microservicecloud
        company.name: www.hec.com
        build.artifactId: $project.artifactId$
        build.version: $project.version$